name: Hello World!
on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04

    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      
      - name: say bye
        run: |
          echo "bye"
      
      - name: say hey
        run: echo "hey"
        
      - name: date
        run: |
          date

      - name: list
        run: | 
          ls